jobs:
  - job: test
    variables:
      PYTHON_VERSION: 3.12
    strategy:
      matrix:
        linux-oldest:
          IMAGE_NAME: ubuntu-22.04
          PYTHON_VERSION: 3.9
          TOXENV: oldest
    pool:
      vmImage: $(IMAGE_NAME)
    steps:
      - template: ../steps/tox-steps.yml
  - job: test_sphinx_builds
    pool:
      vmImage: ubuntu-22.04
    steps:
      - template: ../steps/sphinx-steps.yml
